//
//  MessagesAppViewController.swift
//  StickerSlackiMessageExtension
//
//  Created by neon443 on 18/10/2025.
//

import UIKit
import Messages
import SwiftUI

class MessagesAppViewController: MSMessagesAppViewController {
	var emojiHoarder: EmojiHoarder = EmojiHoarder(localOnly: true, skipIndex: true)
	var tableView: MessagesPackListView!
	var browserView: StickerBrowserViewController!
	
	override func viewDidLoad() {
		super.viewDidLoad()
		emojiHoarder.buildDownloadedStickersSync()
		
		self.tableView = MessagesPackListView(hoarder: emojiHoarder)
		let selRow = UserDefaults.standard.integer(forKey: "selectedPackRowIndex")
		let selPack: EmojiPack?
		if selRow == -1 {
			selPack = nil
		} else {
			selPack = emojiHoarder.emojiPacks[selRow]
		}
		self.browserView = StickerBrowserViewController(emojiHoarder: emojiHoarder, pack: selPack)
		
		let splitView = MessagesRootViewController(
			emojiHoarder: emojiHoarder,
			leading: self.tableView,
			trailing: self.browserView
		)
		self.addChild(splitView)
		splitView.view.translatesAutoresizingMaskIntoConstraints = false
		view.addSubview(splitView.view)
		NSLayoutConstraint.activate([
			splitView.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
			splitView.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
			splitView.view.topAnchor.constraint(equalTo: view.topAnchor),
			splitView.view.bottomAnchor.constraint(equalTo: view.bottomAnchor)
		])
	}
	
	// MARK: - Conversation Handling
	
	override func willBecomeActive(with conversation: MSConversation) {}
	
	override func didResignActive(with conversation: MSConversation) {
		// Called when the extension is about to move from the active to inactive state.
		// This will happen when the user dismisses the extension, changes to a different
		// conversation or quits Messages.
		
		// Use this method to release shared resources, save user data, invalidate timers,
		// and store enough state information to restore your extension to its current state
		// in case it is terminated later.
	}
	
	override func didReceive(_ message: MSMessage, conversation: MSConversation) {
		// Called when a message arrives that was generated by another instance of this
		// extension on a remote device.
		
		// Use this method to trigger UI updates in response to the message.
	}
	
	override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
		// Called when the user taps the send button.
	}
	
	override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
		// Called when the user deletes the message without sending it.
		
		// Use this to clean up state related to the deleted message.
	}
	
	override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
		// Called before the extension transitions to a new presentation style.
		
		// Use this method to prepare for the change in presentation style.
	}
	
	override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
		// Called after the extension transitions to a new presentation style.
		
		// Use this method to finalize any behaviors associated with the change in presentation style.
	}
	
	@objc
	func openStickerSlack() {
		if let url = URL(string: "stickerslack://") {
			self.extensionContext?.open(url) { success in
				print("open url: \(success)")
			}
		}
	}
}
