//
//  MessagesViewController.swift
//  StickerSlackiMessageExtension
//
//  Created by neon443 on 18/10/2025.
//

import UIKit
import Messages
import SwiftUI

class MessagesViewController: MSMessagesAppViewController {
	let dataSource: StickerBrowserDataSource = StickerBrowserDataSource()
	
	override func viewDidLoad() {
		super.viewDidLoad()
		// Do any additional setup after loading the view.
		//		sleep(5)
	}
	
	// MARK: - Conversation Handling
	
	override func willBecomeActive(with conversation: MSConversation) {
		let stickerBrowser = MSStickerBrowserView(frame: .zero, stickerSize: .small)
		stickerBrowser.dataSource = dataSource
		
//		let stackView = UIStackView()
//		stackView.translatesAutoresizingMaskIntoConstraints = false
//		stackView.axis = .vertical
//		for pack in dataSource.hoarder.emojiPacks {
//			let label = UILabel()
//			label.text = pack.name
//			stackView.addArrangedSubview(label)
//			label.translatesAutoresizingMaskIntoConstraints = false
//			NSLayoutConstraint.activate([
////				label.leadingAnchor.constraint(equalTo: stackView.leadingAnchor),
////				label.trailingAnchor.constraint(equalTo: stackView.trailingAnchor),
//				label.heightAnchor.constraint(equalToConstant: 30)
//			])
//		}

		stickerBrowser.translatesAutoresizingMaskIntoConstraints = false
		view.addSubview(stickerBrowser)
//		view.addSubview(stackView)
		NSLayoutConstraint.activate([
			stickerBrowser.topAnchor.constraint(equalTo: view.topAnchor),
			stickerBrowser.bottomAnchor.constraint(equalTo: view.bottomAnchor),
			stickerBrowser.leadingAnchor.constraint(equalTo: view.leadingAnchor),
			stickerBrowser.trailingAnchor.constraint(equalTo: view.trailingAnchor)
		])
		
		guard stickerBrowser.dataSource?.numberOfStickers(in: stickerBrowser) != 0 else {
			let swiftUIView = NoStickersView()
			let hostingController = UIHostingController(rootView: swiftUIView)
			hostingController.view.translatesAutoresizingMaskIntoConstraints = false
			view.addSubview(hostingController.view)
			hostingController.didMove(toParent: self)
			
			let link = UIButton()
			link.setTitle("Open StickerSlack", for: .normal)
			link.setImage(UIImage(systemName: "arrow.up.right.square"), for: .normal)
			link.setTitleColor(.systemBlue, for: .normal)
			link.translatesAutoresizingMaskIntoConstraints = false
			link.addTarget(self, action: #selector(openStickerSlack), for: .touchUpInside)
			view.addSubview(link)

			NSLayoutConstraint.activate([
				hostingController.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
				hostingController.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
				hostingController.view.topAnchor.constraint(equalTo: view.topAnchor),
				hostingController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
				link.centerXAnchor.constraint(equalTo: view.centerXAnchor),
				link.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
				link.heightAnchor.constraint(equalToConstant: 50)
			])

			return
		}
		
//		stickerBrowser.reloadData()
//		view.bringSubviewToFront(stickerBrowser)
		
		// Called when the extension is about to move from the inactive to active state.
		// This will happen when the extension is about to present UI.
		
		// Use this method to configure the extension and restore previously stored state.
	}
	
	override func didResignActive(with conversation: MSConversation) {
		// Called when the extension is about to move from the active to inactive state.
		// This will happen when the user dismisses the extension, changes to a different
		// conversation or quits Messages.
		
		// Use this method to release shared resources, save user data, invalidate timers,
		// and store enough state information to restore your extension to its current state
		// in case it is terminated later.
	}
	
	override func didReceive(_ message: MSMessage, conversation: MSConversation) {
		// Called when a message arrives that was generated by another instance of this
		// extension on a remote device.
		
		// Use this method to trigger UI updates in response to the message.
	}
	
	override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
		// Called when the user taps the send button.
	}
	
	override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
		// Called when the user deletes the message without sending it.
		
		// Use this to clean up state related to the deleted message.
	}
	
	override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
		// Called before the extension transitions to a new presentation style.
		
		// Use this method to prepare for the change in presentation style.
	}
	
	override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
		// Called after the extension transitions to a new presentation style.
		
		// Use this method to finalize any behaviors associated with the change in presentation style.
	}
	
	@objc
	func openStickerSlack() {
		if let url = URL(string: "stickerslack://") {
			self.extensionContext?.open(url) { success in
				print("open url: \(success)")
			}
		}
	}
}
